name: NPM Release

# Runs when a new release is created on GitHub.
# Creates a corresponding NPM release and publishes it.

on:
  release:
    types: [published]

jobs:
  publish_npm:
    runs-on: ubuntu-latest
    steps:
      - name: Setup NodeJS
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Set Package Version
        run: |
          npm version ${{ github.ref }}

      - name: Publish NPM package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_CI_TOKEN }}
          package: npm/package.json
          check-version: false
          dry-run: true  # FIXME
